# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'en-uk'

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Website info
title: The Beit Beaver
description: Your semi-trusted source of fake news at Imperial College London.
logo: assets/images/logo_white.png
logo_dark: assets/images/logo_black.png
logo_mini: assets/images/beaver_white.png
logo_mini_dark: assets/images/beaver_black.png
favicon: assets/images/favicon.png
production_url: https://beitbeaver.com
source_url: https://github.com/beitbeaver/beitbeaver-website/

# Social info
navigation: True # show the navbar links
subscribers: False
twitter: beitbeaver
facebook: beitbeaver

# Disqus
disqus: False
disqus_shortname: myjekyll # replace with disqus username

# Google Analytics
google_analytics: UA-113305143-1

# Prose.io config
prose:
  rooturl: "_posts"
  siteurl: "http://beitbeaver.com"
  media: "assets/images/article-images"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
        - name: "current"
        field:
          element: "hidden"
          value: "post"
      - name: "navigation"
        field:
          element: "hidden"
          value: "True"
      - name: "class"
        field:
          element: "hidden"
          value: "post-template"
      - name: "cover"
        field:
          element: "text"
          label: "Cover image"
          help: "The image which will be displayed at the top of the page"
          value: "assets/images/article-images/breaking-news.png"
          type: "text"
      - name: "title"
        field:
          element: "text"
          label: "Article title"
          help: "The article's title"
          placeholder: "Beit Beaver wins journalism award"
          type: "text"
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "The date and this article was written, in the format, YYYY-MM-DD HH:MM:SS"
          placeholder: "2012-12-12 12:12:12"
      - name: "tags"
        field:
          element: "select"
          label: "Category"
          help: "The category of the article"
          options:
            - name: "The Union"
              value: "union"
            - name: "Imperial College"
              value: "college"
            - name: "Outside of Imperial"
              value: "outside-imperial"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          help: "The tag of the author of this article. If you want to remain anonymous, leave it as beaver. You can add an author by editing _data/authors.yml using git."
          value: "beaver"

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins: [jekyll-paginate, jekyll-feed]
exclude: [vendor]

feed:
  path: feed.xml

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
#safe: False
#lsi: False
#username: myJekyll
#repo: jasper2
#branch: master
#relative_source: ../jasper2/
#destination: ../jasper2-pages/
#production_url:  https://myJekyll.github.io/jasper2/
#source_url:  https://github.com/myJekyll/jasper2/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
